apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: task-system
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: saba0718/aitpp-backend:080a9c5868b901f7aec44225cff21b5efd475d32
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: task-system
spec:
  selector:
    app: backend
  ports:
  - port: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: task-system
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: saba0718/aitpp-worker:080a9c5868b901f7aec44225cff21b5efd475d32
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"