apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: task-system
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: saba0718/aitpp-frontend:9ef9f4a63501b291cd9639783425f521426f90e7
        imagePullPolicy: Always
        ports:
        - containerPort: 5173
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: task-system
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 5173
    targetPort: 5173
    nodePort: 30000